Modifications to run outside Google.
google-research/triangulate pull request #9
Opened 2023-07-25 20:21 UTC by barr

- Update test parameters
  - Fix ABSL Flag handling

Additionally, use Python's tempfile module for program instrumented with probes.

2023-07-26 15:39 UTC, lamblin requested changes

2023-07-26 15:39 UTC, lamblin commented on triangulate/core.py
> +      **_
Silently dropping unexpected arguments looks like a dangerous thing to do, since it silences what could be a useful error signal, as well as static type checks.
If you decide to keep it here, please draw attention to it in a comment.

2023-07-26 15:39 UTC, lamblin commented on triangulate/main.py
> +    env.subject_with_probes._closer.delete = False
Why not call [`tempfile.NamedTemporaryFile(..., delete=False)`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) in the first place?

2023-07-26 15:39 UTC, lamblin commented on triangulate/main.py
> +    env.subject_with_probes._closer.delete = False
Trailing whitespace here, which blocks internal submission for now.

2023-07-31 21:19 UTC, lamblin commented on triangulate/main.py
> +    env.subject_with_probes._closer.delete = False
This one is fine, but there are others...

2023-07-31 21:30 UTC, lamblin approved these changes

2023-08-02 03:27 UTC, lamblin approved these changes
Comments relative to 2 pytype errors internally.

2023-08-02 03:27 UTC, lamblin commented on triangulate/core.py
> +    target_file: TextIO, offset_lines: List[Tuple[int, str]]
Maybe annotate `target_file` as `IO[str]` instead (here and everywhere).
Since `tempfile._TemporaryFileWrapper` is annotated as [`IO[AnyStr]`]( https://github.com/python/typeshed/blob/75c71f324ec564f2c6eaeee81f6b9618db5fb98c/stdlib/tempfile.pyi#L324), I hope this should fix the corresponding pytype error.

2023-08-02 03:27 UTC, lamblin commented on triangulate/core.py
> +    state.codeview.seek(0)
`state.codeview` is a list of strings, so that's a typing error.
Maybe just remove that line?

2023-08-02 03:27 UTC, lamblin commented on triangulate/main.py
> +    probe_output_filename = FLAGS.flag_values_dict()["probe_output_filename"],
Not exactly what I had in mind (I was thinking `FLAGS.subject`, like a few lines above, instead of `flags_dict["subject"]`), but that works as well :)

2023-08-02 21:00 UTC, dan-zheng commented on triangulate/core.py
> +    state.codeview.seek(0)
I agree removing the line is the correct fix. Done.

2023-08-02 21:39 UTC, merged